name: symfony-app
version: '3.8'
services:
# PHP Service
  backend-php:
    restart: always
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
# Nginx Service      
  webserver:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend-php
    links:
      - backend-php  
    networks:
      - app-network
# PostgreSQL Service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testdbuser
      POSTGRES_PASSWORD: testpwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network      
networks:
  app-network:
volumes:
  pgdata:  
