doctrine:
    dbal:
        connections:
            postgres:
                url: '%env(resolve:DATABASE_URL_PG)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            mariadb:
                url: '%env(resolve:DATABASE_URL_MARIA)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
        default_connection: postgres
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Property:
                type: attribute
                dir: '%kernel.project_dir%/src/Property/Entity'
                prefix: 'App\Property\Entity'
                alias: App
            Price:
                type: attribute
                dir: '%kernel.project_dir%/src/Price/Entity'
                prefix: 'App\Price\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
